pipeline {
  agent any

  environment {
    IMAGE_NAME = "DOCKERHUB_USERNAME/recipe-app"
    TAG = "latest"
    SONARQUBE_SERVER = "sonarqube"
  }



    stage('SonarQube Scan') {
      steps {
        withSonarQubeEnv("${SONARQUBE_SERVER}") {
          sh "sonar-scanner"
        }
      }
    }

    stage('Dependency Scan (OWASP)') {
      steps {
        sh """
        dependency-check.sh \
        --project RecipeApp \
        --scan app \
        --format HTML \
        --out dependency-report
        """
      }
    }

    stage('Build Docker Image') {
      steps {
        sh "docker build -t ${IMAGE_NAME}:${TAG} -f docker/Dockerfile ."
      }
    }

    stage('Trivy Image Scan') {
      steps {
        sh "trivy image --exit-code 0 --severity HIGH,CRITICAL ${IMAGE_NAME}:${TAG}"
      }
    }

    stage('Push Image') {
      steps {
        withDockerRegistry(credentialsId: 'dockerhub-creds', url: '') {
          sh "docker push ${IMAGE_NAME}:${TAG}"
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh """
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        """
      }
    }
  }
}
